"use client";

/**
 * src/components/MarkdownContent.tsx
 *
 * Renders markdown text from DynamoDB fields.
 * Converts Obsidian-style [[WikiLink]] and [[WikiLink|Alias]] syntax into
 * external links pointing to https://publish.obsidian.md/tidwell/<PageName>.
 * All other markdown (bold, italic, inline code, paragraphs) is rendered
 * via react-markdown with remark-gfm.
 */

import React, { createContext, useContext } from "react";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import type { Components } from "react-markdown";

// ─── Wiki-link pre-processing ─────────────────────────────────────────────────

const OBSIDIAN_BASE = "https://publish.obsidian.md/tidwell";

/**
 * Strip Obsidian %% comment %% blocks (single-line and multi-line).
 * These are internal authoring notes that should never appear in rendered output.
 */
function stripObsidianComments(text: string): string {
  // %% ... %% may span multiple lines
  return text.replace(/%%[\s\S]*?%%/g, "").replace(/\n{3,}/g, "\n\n").trim();
}

/**
 * Replace [[Target]] and [[Target|Alias]] with a standard markdown link.
 * Target may contain path separators — we use only the last segment as the
 * URL slug (matching how Obsidian Publish resolves short links).
 */
function resolveWikiLinks(text: string): string {
  return text.replace(/\[\[([^\]]+?)\]\]/g, (_match, inner: string) => {
    // Split on | to get optional alias
    const pipeIdx = inner.indexOf("|");
    const target = pipeIdx >= 0 ? inner.slice(0, pipeIdx).trim() : inner.trim();
    const alias  = pipeIdx >= 0 ? inner.slice(pipeIdx + 1).trim() : target;

    // Use the last path segment as the page slug
    const segments = target.split("/");
    const slug = encodeURIComponent(segments[segments.length - 1].trim());
    const href = `${OBSIDIAN_BASE}/${slug}`;

    return `[${alias}](${href})`;
  });
}

// ─── Context: track whether we are inside a class entry ──────────────────────
//
// When rendering a class SRD entry, the H4 renderer adds an ornamental SVG
// divider before subclass-name headings, and the H3 renderer adds one before
// "BACKGROUND QUESTIONS".  This context prevents false positives in non-class
// content (appendix domain cards, adversaries, etc.).

const InsideClassEntryContext = createContext(false);

// ─── Context: track whether we are currently inside a list item ───────────────
//
// react-markdown v10 renders:  ul > li > p > text
// Our custom <li> renderer wraps children in a <li> element, then react-markdown
// calls the <p> renderer for the paragraph inside the list item.
// If <p> emits a block-level element (display:block), the CSS ::marker
// pseudo-element has no inline content to anchor to and appears on its own
// line above the text.  This context lets the <p> renderer know it is inside
// a list item and should emit an inline <span> instead of a block one.

const InsideLiContext = createContext(false);

// ─── Custom renderers ─────────────────────────────────────────────────────────

/**
 * Build react-markdown component overrides.
 *
 * @param linkClassName     Classes applied to every <a> element.
 * @param inlineParagraphs  When true the top-level <p> renderer also uses an
 *   inline <span>.  Pass this when the entire MarkdownContent is placed
 *   directly inside a JSX <li> element (as opposed to a markdown-source list
 *   where the <li> is itself generated by react-markdown).
 */
function makeComponents(linkClassName: string, inlineParagraphs: boolean): Components {
  return {
    // Open all links in a new tab; apply passed-in class
    a({ href, children }) {
      return (
        <a
          href={href}
          target="_blank"
          rel="noopener noreferrer"
          className={linkClassName}
        >
          {children}
        </a>
      );
    },

    /**
     * Paragraph renderer.
     *
     * When rendered inside a list item (tracked via InsideLiContext, or when
     * inlineParagraphs=true for externally-placed <li> wrappers) we emit a
     * plain inline <span> so the text flows on the same line as the ::marker.
     *
     * For normal paragraphs we emit <span class="block"> which preserves the
     * visual block-paragraph layout without introducing an actual <p> element
     * (keeping the caller in control of margin/spacing).
     */
    p({ children }) {
      // eslint-disable-next-line react-hooks/rules-of-hooks
      const insideLi = useContext(InsideLiContext);
      return (insideLi || inlineParagraphs)
        ? <span>{children}</span>
        : <span className="block">{children}</span>;
    },

    // ── Headings ──────────────────────────────────────────────────────────────
    // Tailwind preflight strips default heading styles.  Re-apply semantic
    // headings with classes so they can be further themed via wrapper CSS
    // (e.g. .prose-srd h2 { … }).
    h1({ children }) {
      return <h1 className="mt-6 mb-3 text-2xl font-bold">{children}</h1>;
    },
    h2({ children }) {
      return <h2 className="mt-5 mb-2 text-xl font-bold">{children}</h2>;
    },
    h3({ children }) {
      // Add ornamental divider before "BACKGROUND QUESTIONS" in class entries.
      // eslint-disable-next-line react-hooks/rules-of-hooks
      const isClassEntry = useContext(InsideClassEntryContext);
      const text = typeof children === "string"
        ? children
        : Array.isArray(children)
          ? children.map((c) => (typeof c === "string" ? c : "")).join("")
          : "";
      const upper = text.toUpperCase().trim();
      const isDivider = isClassEntry && upper === "BACKGROUND QUESTIONS";
      return (
        <h3 className={`mt-4 mb-2 text-lg font-semibold${isDivider ? " srd-class-section-break" : ""}`}>
          {children}
        </h3>
      );
    },
    h4({ children }) {
      // Add ornamental divider before subclass name headings in class entries.
      // eslint-disable-next-line react-hooks/rules-of-hooks
      const isClassEntry = useContext(InsideClassEntryContext);
      if (!isClassEntry) {
        return <h4 className="mt-3 mb-1.5 text-base font-semibold">{children}</h4>;
      }
      const text = typeof children === "string"
        ? children
        : Array.isArray(children)
          ? children.map((c) => (typeof c === "string" ? c : "")).join("")
          : "";
      const upper = text.toUpperCase().trim();
      // Subclass names: proper-noun H4s. Exclude tier labels, step labels,
      // and ranger companion headings.
      const isSubclassName =
        upper.length > 0 &&
        !upper.startsWith("TIER ") &&
        !upper.startsWith("STEP ") &&
        !upper.includes("COMPANION") &&
        !upper.includes("WORKING WITH") &&
        !upper.includes("USING ") &&
        !upper.includes("ATTACKING ") &&
        !upper.includes("TAKING ") &&
        !upper.includes("LEVELING ");
      return (
        <h4 className={`mt-3 mb-1.5 text-base font-semibold${isSubclassName ? " srd-class-section-break" : ""}`}>
          {children}
        </h4>
      );
    },
    h5({ children }) {
      return <h5 className="mt-3 mb-1 text-sm font-semibold">{children}</h5>;
    },
    h6({ children }) {
      return <h6 className="mt-2 mb-1 text-sm font-medium">{children}</h6>;
    },

    // ── Block elements ────────────────────────────────────────────────────────
    blockquote({ children }) {
      return (
        <blockquote className="my-3 border-l-4 border-gold-400/40 pl-4 italic text-[#b9baa3]/70">
          {children}
        </blockquote>
      );
    },
    hr() {
      return <hr className="my-6 border-t border-slate-700/60" />;
    },

    // ── Tables ────────────────────────────────────────────────────────────────
    table({ children }) {
      return (
        <div className="my-4 overflow-x-auto rounded-lg border border-slate-700/60">
          <table className="min-w-full text-sm">{children}</table>
        </div>
      );
    },
    thead({ children }) {
      return <thead className="border-b border-slate-700/60 bg-slate-800/50">{children}</thead>;
    },
    tbody({ children }) {
      return <tbody className="divide-y divide-slate-700/30">{children}</tbody>;
    },
    tr({ children }) {
      return <tr>{children}</tr>;
    },
    th({ children }) {
      return (
        <th className="px-3 py-2 text-left text-xs font-semibold uppercase tracking-wider text-[#f7f7ff]/80">
          {children}
        </th>
      );
    },
    td({ children }) {
      return <td className="px-3 py-2 text-[#b9baa3]/85">{children}</td>;
    },

    // Restore list styles stripped by Tailwind preflight.
    // list-outside keeps the bullet in the gutter; text wraps flush with the
    // first character, not back under the bullet.
    ul({ children }) {
      return <ul className="list-disc list-outside pl-5 space-y-0.5">{children}</ul>;
    },
    ol({ children }) {
      return <ol className="list-decimal list-outside pl-5 space-y-0.5">{children}</ol>;
    },

    /**
     * List-item renderer.
     *
     * Sets InsideLiContext so the <p> renderer (called by react-markdown for
     * the paragraph inside the list item) emits an inline <span> rather than
     * a block one — keeping the bullet marker and text on the same line.
     */
    li({ children }) {
      return (
        <InsideLiContext.Provider value={true}>
          <li className="leading-relaxed">{children}</li>
        </InsideLiContext.Provider>
      );
    },

    // ── Inline code & code blocks ─────────────────────────────────────────────
    code({ children, className }) {
      // Fenced code block: rendered as <pre><code class="language-*">
      const isBlock = className?.startsWith("language-");
      if (isBlock) {
        return (
          <code className={`block overflow-x-auto rounded bg-slate-800/60 p-3 text-xs leading-relaxed text-[#b9baa3]/90 ${className}`}>
            {children}
          </code>
        );
      }
      // Inline code
      return (
        <code className="rounded bg-slate-800/60 px-1.5 py-0.5 text-[0.875em] text-[#f7f7ff]/80">
          {children}
        </code>
      );
    },
    pre({ children }) {
      return <pre className="my-3">{children}</pre>;
    },
  };
}

// ─── Component ────────────────────────────────────────────────────────────────

interface MarkdownContentProps {
  /** Raw text from DynamoDB (may contain [[WikiLinks]] and markdown syntax). */
  children: string;
  /** Extra classes applied to the wrapping div. */
  className?: string;
  /**
   * Tailwind classes applied to rendered <a> elements.
   * Defaults to a subtle underline in the steel-blue accent colour.
   */
  linkClassName?: string;
  /**
   * When true, all paragraph nodes are rendered as inline <span> elements
   * (rather than block-level ones) so that text stays on the same line as an
   * enclosing bullet marker or flex sibling.
   *
   * Use this whenever the entire MarkdownContent component is placed directly
   * inside a hand-authored JSX <li> element.  For markdown-source lists
   * (where the <li> is generated by react-markdown itself) the InsideLiContext
   * handles this automatically — you do NOT need inline={true} there.
   */
  inline?: boolean;
  /**
   * When true, enables class-entry-specific ornamental SVG dividers before
   * subclass name headings (H4) and "BACKGROUND QUESTIONS" (H3).
   * Only pass this for class SRD chunks.
   */
  isClassEntry?: boolean;
}

export function MarkdownContent({
  children,
  className = "",
  linkClassName = "underline decoration-[#577399]/60 hover:decoration-[#577399] text-[#8fbad6] hover:text-[#b0d0e6] transition-colors",
  inline = false,
  isClassEntry = false,
}: MarkdownContentProps) {
  const processed = resolveWikiLinks(stripObsidianComments(children));

  return (
    <InsideClassEntryContext.Provider value={isClassEntry}>
      <div className={className}>
        <ReactMarkdown
          remarkPlugins={[remarkGfm]}
          components={makeComponents(linkClassName, inline)}
        >
          {processed}
        </ReactMarkdown>
      </div>
    </InsideClassEntryContext.Provider>
  );
}
