"use client";

/**
 * src/components/MarkdownContent.tsx
 *
 * Renders markdown text from DynamoDB fields.
 * Converts Obsidian-style [[WikiLink]] and [[WikiLink|Alias]] syntax into
 * external links pointing to https://publish.obsidian.md/tidwell/<PageName>.
 * All other markdown (bold, italic, inline code, paragraphs) is rendered
 * via react-markdown with remark-gfm.
 */

import React, { createContext, useContext } from "react";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import type { Components } from "react-markdown";

// ─── Wiki-link pre-processing ─────────────────────────────────────────────────

const OBSIDIAN_BASE = "https://publish.obsidian.md/tidwell";

/**
 * Strip Obsidian %% comment %% blocks (single-line and multi-line).
 * These are internal authoring notes that should never appear in rendered output.
 */
function stripObsidianComments(text: string): string {
  // %% ... %% may span multiple lines
  return text.replace(/%%[\s\S]*?%%/g, "").replace(/\n{3,}/g, "\n\n").trim();
}

/**
 * Replace [[Target]] and [[Target|Alias]] with a standard markdown link.
 * Target may contain path separators — we use only the last segment as the
 * URL slug (matching how Obsidian Publish resolves short links).
 */
function resolveWikiLinks(text: string): string {
  return text.replace(/\[\[([^\]]+?)\]\]/g, (_match, inner: string) => {
    // Split on | to get optional alias
    const pipeIdx = inner.indexOf("|");
    const target = pipeIdx >= 0 ? inner.slice(0, pipeIdx).trim() : inner.trim();
    const alias  = pipeIdx >= 0 ? inner.slice(pipeIdx + 1).trim() : target;

    // Use the last path segment as the page slug
    const segments = target.split("/");
    const slug = encodeURIComponent(segments[segments.length - 1].trim());
    const href = `${OBSIDIAN_BASE}/${slug}`;

    return `[${alias}](${href})`;
  });
}

// ─── Context: track whether we are currently inside a list item ───────────────
//
// react-markdown v10 renders:  ul > li > p > text
// Our custom <li> renderer wraps children in a <li> element, then react-markdown
// calls the <p> renderer for the paragraph inside the list item.
// If <p> emits a block-level element (display:block), the CSS ::marker
// pseudo-element has no inline content to anchor to and appears on its own
// line above the text.  This context lets the <p> renderer know it is inside
// a list item and should emit an inline <span> instead of a block one.

const InsideLiContext = createContext(false);

// ─── Custom renderers ─────────────────────────────────────────────────────────

/**
 * Build react-markdown component overrides.
 *
 * @param linkClassName     Classes applied to every <a> element.
 * @param inlineParagraphs  When true the top-level <p> renderer also uses an
 *   inline <span>.  Pass this when the entire MarkdownContent is placed
 *   directly inside a JSX <li> element (as opposed to a markdown-source list
 *   where the <li> is itself generated by react-markdown).
 */
function makeComponents(linkClassName: string, inlineParagraphs: boolean): Components {
  return {
    // Open all links in a new tab; apply passed-in class
    a({ href, children }) {
      return (
        <a
          href={href}
          target="_blank"
          rel="noopener noreferrer"
          className={linkClassName}
        >
          {children}
        </a>
      );
    },

    /**
     * Paragraph renderer.
     *
     * When rendered inside a list item (tracked via InsideLiContext, or when
     * inlineParagraphs=true for externally-placed <li> wrappers) we emit a
     * plain inline <span> so the text flows on the same line as the ::marker.
     *
     * For normal paragraphs we emit <span class="block"> which preserves the
     * visual block-paragraph layout without introducing an actual <p> element
     * (keeping the caller in control of margin/spacing).
     */
    p({ children }) {
      // eslint-disable-next-line react-hooks/rules-of-hooks
      const insideLi = useContext(InsideLiContext);
      return (insideLi || inlineParagraphs)
        ? <span>{children}</span>
        : <span className="block">{children}</span>;
    },

    // Restore list styles stripped by Tailwind preflight.
    // list-outside keeps the bullet in the gutter; text wraps flush with the
    // first character, not back under the bullet.
    ul({ children }) {
      return <ul className="list-disc list-outside pl-5 space-y-0.5">{children}</ul>;
    },
    ol({ children }) {
      return <ol className="list-decimal list-outside pl-5 space-y-0.5">{children}</ol>;
    },

    /**
     * List-item renderer.
     *
     * Sets InsideLiContext so the <p> renderer (called by react-markdown for
     * the paragraph inside the list item) emits an inline <span> rather than
     * a block one — keeping the bullet marker and text on the same line.
     */
    li({ children }) {
      return (
        <InsideLiContext.Provider value={true}>
          <li className="leading-relaxed">{children}</li>
        </InsideLiContext.Provider>
      );
    },
  };
}

// ─── Component ────────────────────────────────────────────────────────────────

interface MarkdownContentProps {
  /** Raw text from DynamoDB (may contain [[WikiLinks]] and markdown syntax). */
  children: string;
  /** Extra classes applied to the wrapping div. */
  className?: string;
  /**
   * Tailwind classes applied to rendered <a> elements.
   * Defaults to a subtle underline in the steel-blue accent colour.
   */
  linkClassName?: string;
  /**
   * When true, all paragraph nodes are rendered as inline <span> elements
   * (rather than block-level ones) so that text stays on the same line as an
   * enclosing bullet marker or flex sibling.
   *
   * Use this whenever the entire MarkdownContent component is placed directly
   * inside a hand-authored JSX <li> element.  For markdown-source lists
   * (where the <li> is generated by react-markdown itself) the InsideLiContext
   * handles this automatically — you do NOT need inline={true} there.
   */
  inline?: boolean;
}

export function MarkdownContent({
  children,
  className = "",
  linkClassName = "underline decoration-[#577399]/60 hover:decoration-[#577399] text-[#8fbad6] hover:text-[#b0d0e6] transition-colors",
  inline = false,
}: MarkdownContentProps) {
  const processed = resolveWikiLinks(stripObsidianComments(children));

  return (
    <div className={className}>
      <ReactMarkdown
        remarkPlugins={[remarkGfm]}
        components={makeComponents(linkClassName, inline)}
      >
        {processed}
      </ReactMarkdown>
    </div>
  );
}
